spring.application.name=Leavesystem
spring.datasource.url=jdbc:mysql://localhost:3306/leavesystem?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Rithikka123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
springdoc.api-docs.path=/api-docs
jwt.secret=change-this-secret-key-change-this-secret-key
jwt.expiration-minutes=120
